# Generated by Django 4.2 on 2024-04-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('rated', models.CharField(choices=[(0, 'Default'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Best Ever')], max_length=50)),
                ('textOpinion', models.TextField()),
                ('dateOpinion', models.DateField()),
            ],
        ),
    ]
