# Generated by Django 4.2 on 2024-04-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rated',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Very Bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Good'), (5, 'Best Ever')], max_length=50),
        ),
    ]
