# Generated by Django 4.2 on 2024-04-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_opinion_rated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('order_numer', models.CharField(max_length=8)),
                ('textComplaint', models.TextField()),
                ('dateComplaint', models.DateField()),
                ('resolved_type', models.CharField(choices=[(0, 'Default'), (1, 'return order'), (2, 'save order and 20% discout'), (3, 'change thing/s')])),
                ('status', models.CharField(choices=[(0, 'Default'), (1, 'New'), (2, 'In progress'), (3, 'Resolved')])),
            ],
        ),
    ]
